### ISSUE TITLE
Spawn Confict

### ISSUE THREAD

**Issue by Purrkour** [LyraelRayne/StacysWolves#42]
When Ever i Load my server with the mod everythings fine but once i try to spawn a wolf with its spawn egg it takes me out of my server and says a interal server error and in the console it yells this at me....
idk why this is happening >.>

[22:55:04 WARN]: Caused by: java.lang.NullPointerException
>
[22:55:04 WARN]: 	at au.lyrael.stacywolves.entity.wolf.EntityWolfBase.isCreatureType(EntityWolfBase.java:1173)
>
[22:55:04 WARN]: 	at org.spigotmc.ActivationRange.initializeEntityActivationType(ActivationRange.java:58)
>
[22:55:04 WARN]: 	at net.minecraft.entity.Entity.<init>(Entity.java:180)
>
[22:55:04 WARN]: 	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:141)
>
[22:55:04 WARN]: 	at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:75)
>
[22:55:04 WARN]: 	at net.minecraft.entity.EntityCreature.<init>(EntityCreature.java:38)
>
[22:55:04 WARN]: 	at net.minecraft.entity.EntityAgeable.<init>(EntityAgeable.java:47)
>
[22:55:04 WARN]: 	at net.minecraft.entity.passive.EntityAnimal.<init>(SourceFile:26)
>
[22:55:04 WARN]: 	at net.minecraft.entity.passive.EntityTameable.<init>(SourceFile:23)
>
[22:55:04 WARN]: 	at au.lyrael.stacywolves.entity.wolf.EntityWolfBase.<init>(EntityWolfBase.java:98)
>
[22:55:04 WARN]: 	at au.lyrael.stacywolves.entity.wolf.EntityCowWolf.<init>(EntityCowWolf.java:26)
>
[22:55:04 WARN]: 	... 10 more
[22:55:04 WARN]: java.lang.reflect.InvocationTargetException
>
[22:55:04 WARN]: 	at sun.reflect.GeneratedConstructorAccessor101.newInstance(Unknown Source)
>
[22:55:04 WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>
[22:55:04 WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>
[22:55:04 WARN]: 	at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:197)
>
[22:55:04 WARN]: 	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:248)
>
[22:55:04 WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920)
>
[22:55:04 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
>
[22:55:04 WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
>
[22:55:04 WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
>
[22:55:04 WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by LyraelRayne** [comment]
Hi there. Sorry it's taken so long to get back to you. I have tried to reproduce this without any luck. Can I confirm a couple of things:

1.  Are you running any other mods? Which mods? (include versions)
1.  Are you running the latest version of the mod (1.1.2a)?
1. Which version of Java are  you running?
1. Which server are you running? 
1. Can you upload a copy of the full client and server logs (latest.log) for a session where it crashed? (preferably containing only the one session). 
1. Is there a specific wolf that this is happening for?

**Comment by LyraelRayne** [comment]
See #44 for progress on this issue.
